namespace: aimusei
nameBase: "aimusei"

replicaCount: 1

image:
  repository: vincenzopapalia/backend
  tag: "3.5.5"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8090

config:
  contextPath: /aimusei/api
  mongoUri: "mongodb://mongo-service:27017/aimusei?connectTimeoutMS=30000&socketTimeoutMS=30000"
  appKey: "keytest123123"

  # datasources.env
  mongoHost: "mongo-service"
  mongoDatabase: "aimusei"
  forwardHeadersStrategy: NATIVE
  
  s3:
    endpoint: "https://s3-nord.iaas01.console.polostrategiconazionale.it:9021"
    region: "us-east-1"
    accessKey: "admin-psn10012201973"
    secretKey: "v+F9JBy2lx6jvzTaUcADyBoR/lfyQfaxIpnisss5"
    pathStyleAccessEnabled: true
    chunkedEncodingEnabled: true
    checksumValidationEnabled: false
  
  aiservice:
    uri: "http://aigateway-middleware.accessibilita.svc.cluster.local:80"
    endpoint: "/aiservice/airequest"
    namespace: "aimusei"
    serviceAccount: "aimusei-sa"
    enabled: true

  envVars:
    SPRING_DATA_MONGODB_URI: "mongodb://mongo-service:27017/aimusei?connectTimeoutMS=30000&socketTimeoutMS=30000" # puoi anche metterla qui
    AI_GATEWAY_URI: "http://aigateway-middleware.accessibilita.svc.cluster.local:80"
    AI_GATEWAY_ENDPOINT: "/aiservice/airequest"
    K8S_CLIENT_SERVICE_ACCOUNT_NAME: "aimusei-sa"
    K8S_CLIENT_NAMESPACE: "aimusei"

serviceAccount:
  create: true
  name: "aimusei-sa"
  automount: true

rbac:
  create: true
  createTokenRequester: true
