namespace: aimusei
nameBase: "aimusei"

replicaCount: 1

image:
  repository: vincenzopapalia/backend
  tag: "3.5.23"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8090

config:
  contextPath: /aimusei/api
  mongoUri: "mongodb://mongo-service:27017/aimusei?connectTimeoutMS=30000&socketTimeoutMS=30000"
  appKey: "keytest123123"
  
  multipart:
    maxFileSize: "20MB"
    maxRequestSize: "50MB"

  extraProperties: |
    scheduler.opere.delay-ms=10000
    scheduler.jobs.delay-ms=30000
    scheduler.pulitore.delay-ms=86400000
    csv.batch-size=100
    preleaver.batch-size=100
    polling.interval-seconds=60
    polling.timeout-minutes=60
    polling.max-consecutive-errors=3
    cleaner.timeout-hours=4
    scheduling.config.await-termination=30
    smn.auth.issuer-uri=MiBACT
    smn.auth.base-url=https://smn-coll.museiitaliani.it/api/v1
    keycloak.auth.issuer-uri=https://login-coll.museiitaliani.it/realms/AD-Arte-users
    keycloak.auth.userinfo-uri=https://login-coll.museiitaliani.it/realms/AD-Arte-users/protocol/openid-connect/userinfo
    secret=6z1kf4nkx35y5ix28lm3pe2mraqtnrl468gvt4i0
    springdoc.api-docs.enabled=false
    springdoc.swagger-ui.enabled=false

  # datasources.env
  mongoHost: "mongo-service"
  mongoDatabase: "aimusei"
  forwardHeadersStrategy: NATIVE
  
  s3:
    endpoint: "https://s3-nord.iaas01.console.polostrategiconazionale.it:9021"
    region: "us-east-1"
    accessKey: "admin-psn10012201973"
    secretKey: "v+F9JBy2lx6jvzTaUcADyBoR/lfyQfaxIpnisss5"
    pathStyleAccessEnabled: true
    chunkedEncodingEnabled: true
    checksumValidationEnabled: false
  
  aiservice:
    uri: "http://aigateway-middleware.accessibilita.svc.cluster.local:80"
    endpoint: "/aiservice/airequest"
    namespace: "aimusei"
    serviceAccount: "aimusei-sa"
    enabled: true

  envVars:
    SPRING_DATA_MONGODB_URI: "mongodb://mongo-service:27017/aimusei?connectTimeoutMS=30000&socketTimeoutMS=30000" # puoi anche metterla qui
    AI_GATEWAY_URI: "http://aigateway-middleware.accessibilita.svc.cluster.local:80"
    AI_GATEWAY_ENDPOINT: "/aiservice/airequest"
    K8S_CLIENT_SERVICE_ACCOUNT_NAME: "aimusei-sa"
    K8S_CLIENT_NAMESPACE: "aimusei"
    APP_BASE_URL: "https://api-coll.museiitaliani.it"

hostAliases:
  - ip: "95.100.171.215"
    hostnames:
      - "akamaicdn.museiitaliani.it"

serviceAccount:
  create: true
  name: "aimusei-sa"
  automount: true

rbac:
  create: true
  createTokenRequester: true
