<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>it.prismaprogetti</groupId>
		<artifactId>aimusei-build</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
    </parent>
    <groupId>com.leonardo.aiservice</groupId>
    <artifactId>aiservice</artifactId>
    <version>1.0.2</version>
    <name>AI gateway library</name>
    <description>Libreria per accedere al servizio AIGateway all'interno di un cluster Kubernetes.</description>

    <properties>
        <maven.compiler.release>21</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.leonardo.aiservice</groupId>
            <artifactId>common</artifactId>
            <version>1.0.3</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        <dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java</artifactId>
            <version>23.0.0-legacy</version> <!-- to change -->
        </dependency>
    </dependencies>

</project>