namespace: aimusei
nameBase: "aimusei"
names:
  deployment: aimusei-fe-deployment
  service: aimusei-fe-service
  ingress: aimusei-ingress

replicaCount: 1

image:
  repository: vincenzopapalia/frontend
  tag: "2.13"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingresses:
  - enabled: true
    name: aimusei-ingress-locale
    className: "nginx"
    host: "aimusei.local"
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "10m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "75"
    paths:
      - path: /aimusei/api/
        pathType: Prefix
        serviceName: aimusei-be-service
        servicePort: 8090
      - path: /aimusei/
        pathType: Prefix
        serviceName: aimusei-fe-service
        servicePort: 80

  - enabled: true
    name: aimusei-ingress-pubblico
    className: "nginx"
    host: "api-coll.museiitaliani.it"
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "75"
    paths:
      - path: /aimusei/api
        pathType: Prefix
        serviceName: aimusei-be-service
        servicePort: 8090
      - path: /aimusei
        pathType: Prefix
        serviceName: aimusei-fe-service
        servicePort: 80
