spring.application.name=aimusei
server.servlet.context-path=/aimusei

aiservice.uri=http://aigateway-middleware.accessibilita.svc.cluster.local:80
aiservice.endpoint=/aiservice/airequest
aiservice.k8s.namespace=aimusei
aiservice.k8s.service-account=aimusei-sa
aiservice.k8s.enabled=true




spring.cloud.aws.s3.endpoint=https://s3-nord.iaas01.console.polostrategiconazionale.it:9021
spring.cloud.aws.s3.region=us-east-1
spring.cloud.aws.credentials.access-key=admin-psn10012201973
spring.cloud.aws.credentials.secret-key=chiedimi