spring.application.name=aimusei
server.servlet.context-path=/aimusei

aiservice.uri=http://aigateway-middleware.accessibilita.svc.cluster.local:80
aiservice.endpoint=/aiservice/airequest
aiservice.k8s.namespace=aimusei
aiservice.k8s.service-account=aimusei-sa
aiservice.k8s.enabled=true