aiservice.uri=http://aigateway-middleware.accessibilita.svc.cluster.local:80
aiservice.endpoint=/aiservice/airequest
aiservice.k8s.namespace=accessibilita
aiservice.k8s.service-account=middleware
aiservice.k8s.enabled=false